GET  http://localhost:3000/products

DELETE  http://localhost:3000/products/6


# POST http://localhost:3000/products
# Content-Type: application/json

# {
#     "name": "producto 4",
#     "price": 10.54
# }



# DELETE  http://localhost:3000/products/2

# PUT  http://localhost:3000/products/2
# Content-Type: application/json

# {
#     "name": "producto test editado 2",
#     "price": 12
# }

# GET  http://localhost:3000/products/0

# GET  http://localhost:3000/products

# POST http://localhost:3000/products
# Content-Type: application/json

# {
#     "name": "producto test",
#     "price": 10.54
# }